export const animals = [
  {
    title: 'Kullanıcı belirlediği isim',
    gender: 'Erkek',
    age: 1,
    date: 'aylık',
    categories: 'Kedi',
    thumbnail: 'https://dummyimage.com/256x256/000/fff',
    description: 'Kullanıcı belirlediği açıklama',
  },
  {
    title: 'Kullanıcı belirlediği isim',
    gender: 'Erkek',
    age: 6,
    date: 'aylık',
    categories: 'Kedi',
    thumbnail: 'https://dummyimage.com/256x256/000/fff',
    description: 'Kullanıcı belirlediği açıklama',
  },
  {
    title: 'Kullanıcı belirlediği isim',
    gender: 'Dişi',
    age: 4,
    date: 'günlük',
    categories: 'Kedi',
    thumbnail: 'https://dummyimage.com/256x256/000/fff',
    description: 'Kullanıcı belirlediği açıklama',
  },
  {
    title: 'Kullanıcı belirlediği isim',
    gender: 'Dişi',
    age: 2,
    date: 'yaşında',
    categories: 'Köpek',
    thumbnail: 'https://dummyimage.com/256x256/000/fff',
    description: 'Kullanıcı belirlediği açıklama',
  },
  {
    title: 'Kullanıcı belirlediği isim',
    gender: 'Erkek',
    age: 1,
    date: 'yaşında',
    categories: 'Köpek',
    thumbnail: 'https://dummyimage.com/256x256/000/fff',
    description: 'Kullanıcı belirlediği açıklama',
  },
  {
    title: 'Kullanıcı belirlediği isim',
    gender: 'Erkek',
    age: 1,
    date: 'yaşında',
    categories: 'Köpek',
    thumbnail: 'https://dummyimage.com/256x256/000/fff',
    description: 'Kullanıcı belirlediği açıklama',
  },
  {
    title: 'Kullanıcı belirlediği isim',
    gender: 'Erkek',
    age: 1,
    date: 'yaşında',
    categories: 'Köpek',
    thumbnail: 'https://dummyimage.com/256x256/000/fff',
    description: 'Kullanıcı belirlediği açıklama',
  },
  {
    title: 'Kullanıcı belirlediği isim',
    gender: 'Erkek',
    age: 1,
    date: 'yaşında',
    categories: 'Köpek',
    thumbnail: 'https://dummyimage.com/256x256/000/fff',
    description: 'Kullanıcı belirlediği açıklama',
  },
  {
    title: 'Kullanıcı belirlediği isim',
    gender: 'Erkek',
    age: 1,
    date: 'yaşında',
    categories: 'Köpek',
    thumbnail: 'https://dummyimage.com/256x256/000/fff',
    description: 'Kullanıcı belirlediği açıklama',
  },
  {
    title: 'Kullanıcı belirlediği isim',
    gender: 'Erkek',
    age: 1,
    date: 'yaşında',
    categories: 'Köpek',
    thumbnail: 'https://dummyimage.com/256x256/000/fff',
    description: 'Kullanıcı belirlediği açıklama',
  },
  {
    title: 'Kullanıcı belirlediği isim',
    gender: 'Erkek',
    age: 1,
    date: 'yaşında',
    categories: 'Köpek',
    thumbnail: 'https://dummyimage.com/256x256/000/fff',
    description: 'Kullanıcı belirlediği açıklama',
  },
  {
    title: 'Kullanıcı belirlediği isim',
    gender: 'Erkek',
    age: 1,
    date: 'yaşında',
    categories: 'Köpek',
    thumbnail: 'https://dummyimage.com/256x256/000/fff',
    description: 'Kullanıcı belirlediği açıklama',
  },
  {
    title: 'Kullanıcı belirlediği isim',
    gender: 'Erkek',
    age: 1,
    date: 'yaşında',
    categories: 'Köpek',
    thumbnail: 'https://dummyimage.com/256x256/000/fff',
    description: 'Kullanıcı belirlediği açıklama',
  },
  {
    title: 'Kullanıcı belirlediği isim',
    gender: 'Erkek',
    age: 1,
    date: 'yaşında',
    categories: 'Köpek',
    thumbnail: 'https://dummyimage.com/256x256/000/fff',
    description: 'Kullanıcı belirlediği açıklama',
  },
  {
    title: 'Kullanıcı belirlediği isim',
    gender: 'Erkek',
    age: 1,
    date: 'yaşında',
    categories: 'Köpek',
    thumbnail: 'https://dummyimage.com/256x256/000/fff',
    description: 'Kullanıcı belirlediği açıklama',
  },
  {
    title: 'Kullanıcı belirlediği isim',
    gender: 'Erkek',
    age: 1,
    date: 'yaşında',
    categories: 'Köpek',
    thumbnail: 'https://dummyimage.com/256x256/000/fff',
    description: 'Kullanıcı belirlediği açıklama',
  },
]
